services:
  - type: web
    name: tds-proj1-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "8909133888:AAE0c3NC6UITuQ23cfInf3-P4uuxITofdr8"
      - key: AIPIPE_API_KEY
        value: "eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IjI0ZjMwMDE2NzZAZHMuc3R1ZHkuaWl0bS5hYy5pbiIsImlhdCI6MTc4NTM0ODA2MSwiaXNzIjoiaHR0cHM6Ly9haXBpcGUub3JnIiwiYXVkIjoiYWlwaXBlLWFwaSIsImV4cCI6MTc4NTk1Mjg2MX0.nmtXGmYuzZTcdf5yYIZAhrTynOlc94JTr2JIYtEqhQ0"
      - key: AIPIPE_BASE_URL
        value: "https://aipipe.org/openai/v1"
      - key: LLM_MODEL
        value: "gpt-4o-mini"
      - key: LOG_BASE_URL
        sync: false